[package]
name = "bevy-2d"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
bevy = "0.12.0"
bevy-inspector-egui = "0.21.0"
