mod control_entities_that_are_able_to_jump_and_able_to_control;
mod control_entities_that_are_able_to_move_and_able_to_control;

pub use control_entities_that_are_able_to_jump_and_able_to_control::control_entities_that_are_able_to_jump_and_able_to_control;
pub use control_entities_that_are_able_to_move_and_able_to_control::control_entities_that_are_able_to_move_and_able_to_control;
